return {
  -- CATPPUCCIN --
  -- {
  --   "catppuccin",
  --   name = "catppuccin",
  --   priority = 1000,
  --   lazy = false,
  --   opts = {
  --     flavour = "mocha",
  --     background = {
  --       light = "latte",
  --       dark = "mocha",
  --     },
  --     term_colors = false,
  --     transparent_background = true,
  --     float = {
  --       transparent = true,
  --       solid = true,
  --       -- single = true,
  --     },
  --     custom_highlights = function(colors)
  --       return {
  --         TabLineSel = {
  --           fg = colors.flamingo,
  --         },
  --         TabLine = {
  --           fg = colors.pink,
  --         },
  --         CmpBorder = {
  --           fg = colors.pink,
  --           bg = colors.pink,
  --         },
  --         Pmenu = {
  --           bg = colors.none,
  --         },
  --       }
  --     end,
  --
  --     integrations = {
  --       bufferline = false,
  --       cmp = true,
  --       treesitter = true,
  --       snacks = {
  --         enabled = true,
  --       },
  --       blink_cmp = {
  --         style = "bordered",
  --       },
  --     },
  -- styles = {
  --   comments = {},
  --   conditionals = {},
  --   loops = {},
  --   functions = {},
  --   keywords = {},
  --   strings = {},
  --   variables = {},
  --   numbers = {},
  --   booleans = {},
  --   properties = {},
  --   types = {},
  -- },
  -- color_overrides = {
  --   mocha = {
  --     base = "#000000",
  --     mantle = "#000000",
  --     crust = "#000000",
  --   },
  -- },
  -- default_integrations = true,
  --   },
  -- },

  -- ROSE-PINE --
  -- {
  --   "rose-pine/neovim",
  --   name = "rose-pine",
  --   lazy = false,
  --   config = function()
  --     require("rose-pine").setup({
  --       variant = "moon",
  --       dark_variant = "moon",
  --       styles = {
  --         transparency = true,
  --         bold = true,
  --         italic = true,
  --       },
  --       enable = {
  --         terminal = true,
  --         legacy_highlights = true,
  --         migrations = true,
  --       },
  --       groups = {
  --         border = "muted",
  --         link = "iris",
  --         panel = "surface",
  --         error = "love",
  --         hint = "iris",
  --         info = "foam",
  --         note = "pine",
  --         todo = "rose",
  --         warn = "gold",
  --         git_add = "foam",
  --         git_change = "rose",
  --         git_delete = "love",
  --         git_dirty = "rose",
  --         git_ignore = "muted",
  --         git_merge = "iris",
  --         git_rename = "pine",
  --         git_stage = "iris",
  --         git_text = "rose",
  --         git_untracked = "subtle",
  --         h1 = "iris",
  --         h2 = "foam",
  --         h3 = "rose",
  --         h4 = "gold",
  --         h5 = "pine",
  --         h6 = "foam",
  --       },
  --       highlight_groups = {
  --         Normal = { bg = nil },
  --         NormalFloat = { bg = nil },
  --         SignColumn = { bg = nil },
  --         LineNr = { bg = nil },
  --         EndOfBuffer = { bg = nil },
  --       },
  --     })
  --     vim.cmd("colorscheme rose-pine-moon")
  --   end,
  -- },

  -- GRUV BOX --
  -- {
  --   "ellisonleao/gruvbox.nvim",
  --   priority = 1000,
  --   config = true,
  -- },

  -- {
  --   "Shatur/neovim-ayu",
  --   config = function()
  --     require("ayu").setup({
  --       terminal = true,
  --       mirage = true,
  --       overrides = {},
  --     })
  --   end,
  -- },

  -- ELDRITCH --
  -- {
  --   "eldritch-theme/eldritch.nvim",
  --   lazy = false,
  --   priority = 1000,
  --   opts = {
  --     transparent = true,
  --     terminal_colors = true,
  --     styles = {
  --       comments = { italic = true },
  --       keywords = { italic = true },
  --       functions = {},
  --       variables = {},
  --       sidebars = "dark",
  --       floats = "dark",
  --     },
  --     on_highlights = function(highlights, colors)
  --       highlights.Normal = { bg = nil } -- Ensure main background is transparent
  --       highlights.NormalFloat = { bg = nil } -- Ensure floating windows are transparent
  --       highlights.SignColumn = { bg = nil } -- Ensure sign column is transparent
  --       highlights.LineNr = { bg = nil } -- Ensure line numbers are transparent
  --     end,
  --   },
  -- },
}
